{- This file is generated by the 'scripts/gen_package.py' script -}
{ Alerting =
    ./schemas/Alerting.dhall sha256:ce643c5ebae49afea906bbdcd95f32e606661f7d21c5bebf3ee9d1f526ba8139
, AlertingRule =
    ./schemas/AlertingRule.dhall sha256:6c9561bbfb6684b331918d4ac468c8bdb5c23ebb9395eaf4909e295884e6d042
, Alertmanager =
    ./schemas/Alertmanager.dhall sha256:17f6827624584a0823a1326e80720e166c589a4b8efb3db75340e30d5b844d13
, Annotations =
    ./schemas/Annotations.dhall sha256:bdd224e000972744e52c7cedba02817c91d147e99dc89ba68b03454c2af4470d
, AzureSdConfig =
    ./schemas/AzureSdConfig.dhall sha256:81a1bf11fb9dc588941bd83400ed571298585a700a53e858456806f7ea3b8ce2
, BasicAuth =
    ./schemas/BasicAuth.dhall sha256:45bfe2d23482278d5705e023814d8ee09d1f410c87cdf18d703ebd932e98340e
, Config =
    ./schemas/Config.dhall sha256:393c5259754effdafd4376ee9307db221b56de974d48aed3ea6e5fb246ecc265
, ConsulSdConfig =
    ./schemas/ConsulSdConfig.dhall sha256:81a1bf11fb9dc588941bd83400ed571298585a700a53e858456806f7ea3b8ce2
, DnsSdConfig =
    ./schemas/DnsSdConfig.dhall sha256:81a1bf11fb9dc588941bd83400ed571298585a700a53e858456806f7ea3b8ce2
, Ec2SdConfig =
    ./schemas/Ec2SdConfig.dhall sha256:81a1bf11fb9dc588941bd83400ed571298585a700a53e858456806f7ea3b8ce2
, FileSdConfig =
    ./schemas/FileSdConfig.dhall sha256:89e937a8dd76180263b6136c72151d2ab762a72d0b7f75e9266a5b105b4e7891
, GceSdConfig =
    ./schemas/GceSdConfig.dhall sha256:81a1bf11fb9dc588941bd83400ed571298585a700a53e858456806f7ea3b8ce2
, Global =
    ./schemas/Global.dhall sha256:5334fecacdb397aabfb682c11b04bce33337b2048d2eebff9c9e3651f7631f95
, Group =
    ./schemas/Group.dhall sha256:c494ccd175aff98356854a3b8e86f3b8327f0c8ce17ef04bd63a476f334fae59
, KubernetesSdConfig =
    ./schemas/KubernetesSdConfig.dhall sha256:81a1bf11fb9dc588941bd83400ed571298585a700a53e858456806f7ea3b8ce2
, Labels =
    ./schemas/Labels.dhall sha256:81a1bf11fb9dc588941bd83400ed571298585a700a53e858456806f7ea3b8ce2
, MarathonSdConfig =
    ./schemas/MarathonSdConfig.dhall sha256:81a1bf11fb9dc588941bd83400ed571298585a700a53e858456806f7ea3b8ce2
, NerveSdConfig =
    ./schemas/NerveSdConfig.dhall sha256:81a1bf11fb9dc588941bd83400ed571298585a700a53e858456806f7ea3b8ce2
, OpenstackSdConfig =
    ./schemas/OpenstackSdConfig.dhall sha256:81a1bf11fb9dc588941bd83400ed571298585a700a53e858456806f7ea3b8ce2
, Params =
    ./schemas/Params.dhall sha256:970cc0bccc746f3e5452ed995b8415cebc9a750a6bd006efcf3dc29e9de0bead
, QueueConfig =
    ./schemas/QueueConfig.dhall sha256:06f99d5d84cc28959b3e36953eed9c5bcf18c187b16446a2bc7a8d8fb637447d
, RelabelConfig =
    ./schemas/RelabelConfig.dhall sha256:d15bbafc8a991eafe6a8afcacfdcc8f5f46c4101a31d550e2065e9ad5799c0e0
, RemoteRea =
    ./schemas/RemoteRea.dhall sha256:951b8cf49be6f54fd78f2c863953c894d1bf493d46ae7263d8111fe6d6507670
, RemoteWrit =
    ./schemas/RemoteWrit.dhall sha256:94ca73cf1d72bb5f10ac2a334a00fea9b3fb3a2a1537faecea89f3498f223acb
, RulesConfig =
    ./schemas/RulesConfig.dhall sha256:3835e1d55da2d1f0cbdc8e303d2001580a9ac92962a498c6bbea502bc3c17420
, ScrapeConfig =
    ./schemas/ScrapeConfig.dhall sha256:1aa614c25baed7229075a77152342b75232fc46623a09a597fc9579377920b83
, ServersetSdConfig =
    ./schemas/ServersetSdConfig.dhall sha256:81a1bf11fb9dc588941bd83400ed571298585a700a53e858456806f7ea3b8ce2
, StaticConfig =
    ./schemas/StaticConfig.dhall sha256:99ff72dd0376432b50520cc706e11e49b7e8206c1ce469c25b0796bcb3dad6c5
, TlsConfig =
    ./schemas/TlsConfig.dhall sha256:52f95170e3f642908f6b4dcee3fb8bfed81080f908f28167c9eda351572bdd99
, TritonSdConfig =
    ./schemas/TritonSdConfig.dhall sha256:81a1bf11fb9dc588941bd83400ed571298585a700a53e858456806f7ea3b8ce2
}
