{- This file is generated by the 'scripts/gen_package.py' script -}
{ Alerting =
    ./schemas/Alerting.dhall sha256:4db0cfe1a8327dd3be1554b5be5b10cfcc76afa8a108e77d9be35fc04bec5a9e
, AlertingRule =
    ./schemas/AlertingRule.dhall sha256:25ba4a242e4b6eda8528c7289935d49f9b6fa4a490f1b17e8031b61dbffd3e67
, Alertmanager =
    ./schemas/Alertmanager.dhall sha256:70ca6aa20d899e3cf23b4a4b140853a28f087491e90314534774b490021afc34
, Annotations =
    ./schemas/Annotations.dhall sha256:bdd224e000972744e52c7cedba02817c91d147e99dc89ba68b03454c2af4470d
, AzureSdConfig =
    ./schemas/AzureSdConfig.dhall sha256:81a1bf11fb9dc588941bd83400ed571298585a700a53e858456806f7ea3b8ce2
, BasicAuth =
    ./schemas/BasicAuth.dhall sha256:45bfe2d23482278d5705e023814d8ee09d1f410c87cdf18d703ebd932e98340e
, Config =
    ./schemas/Config.dhall sha256:de93f22d90879b1b6297cff2b8680c313155f042c179fbf51d27946a3cd84a75
, ConsulSdConfig =
    ./schemas/ConsulSdConfig.dhall sha256:81a1bf11fb9dc588941bd83400ed571298585a700a53e858456806f7ea3b8ce2
, DnsSdConfig =
    ./schemas/DnsSdConfig.dhall sha256:81a1bf11fb9dc588941bd83400ed571298585a700a53e858456806f7ea3b8ce2
, Ec2SdConfig =
    ./schemas/Ec2SdConfig.dhall sha256:81a1bf11fb9dc588941bd83400ed571298585a700a53e858456806f7ea3b8ce2
, FileSdConfig =
    ./schemas/FileSdConfig.dhall sha256:89e937a8dd76180263b6136c72151d2ab762a72d0b7f75e9266a5b105b4e7891
, GceSdConfig =
    ./schemas/GceSdConfig.dhall sha256:81a1bf11fb9dc588941bd83400ed571298585a700a53e858456806f7ea3b8ce2
, Global =
    ./schemas/Global.dhall sha256:e69394f8f233963537029c98996154dc662a4b25382ffac9b86c6e4c2596b0e4
, Group =
    ./schemas/Group.dhall sha256:47af257cb60878f7d97f55f36aae30dd39b86a5fb24eb8a19a21fea26d287286
, KubernetesSdConfig =
    ./schemas/KubernetesSdConfig.dhall sha256:81a1bf11fb9dc588941bd83400ed571298585a700a53e858456806f7ea3b8ce2
, Labels =
    ./schemas/Labels.dhall sha256:d43fc8bfb08a3b5ee856c1c8d77a404e0c421f6633779268047c4f2f3cb0a09c
, MarathonSdConfig =
    ./schemas/MarathonSdConfig.dhall sha256:81a1bf11fb9dc588941bd83400ed571298585a700a53e858456806f7ea3b8ce2
, NerveSdConfig =
    ./schemas/NerveSdConfig.dhall sha256:81a1bf11fb9dc588941bd83400ed571298585a700a53e858456806f7ea3b8ce2
, OpenstackSdConfig =
    ./schemas/OpenstackSdConfig.dhall sha256:81a1bf11fb9dc588941bd83400ed571298585a700a53e858456806f7ea3b8ce2
, Params =
    ./schemas/Params.dhall sha256:970cc0bccc746f3e5452ed995b8415cebc9a750a6bd006efcf3dc29e9de0bead
, QueueConfig =
    ./schemas/QueueConfig.dhall sha256:06f99d5d84cc28959b3e36953eed9c5bcf18c187b16446a2bc7a8d8fb637447d
, RelabelConfig =
    ./schemas/RelabelConfig.dhall sha256:d15bbafc8a991eafe6a8afcacfdcc8f5f46c4101a31d550e2065e9ad5799c0e0
, RemoteRea =
    ./schemas/RemoteRea.dhall sha256:dec3c2a9f6ca4d6dbbe03066f150cb852d965e96785444768941d9c00acebcaa
, RemoteWrit =
    ./schemas/RemoteWrit.dhall sha256:94ca73cf1d72bb5f10ac2a334a00fea9b3fb3a2a1537faecea89f3498f223acb
, RulesConfig =
    ./schemas/RulesConfig.dhall sha256:23cfc10f4802ddf4ecc613ffc05328e2bf5f47a7633511b6b89a64d9626b74c0
, ScrapeConfig =
    ./schemas/ScrapeConfig.dhall sha256:e45f9b1d86d48bcc24b9e94f749c93a6049629d92b906571879c7c3cb8dcce15
, ServersetSdConfig =
    ./schemas/ServersetSdConfig.dhall sha256:81a1bf11fb9dc588941bd83400ed571298585a700a53e858456806f7ea3b8ce2
, StaticConfig =
    ./schemas/StaticConfig.dhall sha256:4e5423d914c3ecae215961224d00e7b3b71a285f7254e2172b1e586fcbe325e3
, TlsConfig =
    ./schemas/TlsConfig.dhall sha256:52f95170e3f642908f6b4dcee3fb8bfed81080f908f28167c9eda351572bdd99
, TritonSdConfig =
    ./schemas/TritonSdConfig.dhall sha256:81a1bf11fb9dc588941bd83400ed571298585a700a53e858456806f7ea3b8ce2
}
